---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install Duplicity library requirements
  ansible.builtin.package:
    name: "{{ _duplicity_dependent_packages }}"
    state: present
  when: install_duplicity

- name: Install Duplicity and backend support Python modules
  ansible.builtin.pip:
    name:
      - "{{ duplicity_install_package }}"
      - dropbox
    virtualenv: "{{ duplicity_venv_path }}"
    virtualenv_command: python3 -m venv
    state: present
  when: install_duplicity

- name: Install a helper script to run duplicity in the virtualenv
  ansible.builtin.template:
    src: duplicity-helper.sh.j2
    dest: "{{ duplicity_binary }}"
    mode: 0755
  when: install_duplicity

- name: Template out credentials file
  ansible.builtin.template:
    src: duplicity-backup.env.j2
    dest: /etc/{{ duplicity_install_name }}-backup.env
    owner: root
    group: root
    mode: 0600

# Run commands manually
- name: Run manual backups
  ansible.builtin.command: "{{ duplicity_binary }} --full-if-older-than {{ full_backup_after }} {{ item.path }} {{ (item.backup_url_stem | default(backup_url_stem)).rstrip('/') }}/{{ (item.name | default(item.path)).strip('/') }}"  # noqa 204 - Command line too long, can't wrap
  environment: "{{ backup_env_vars | combine({'PASSPHRASE': gpg_key}) }}"
  loop: "{{ duplicity_target_paths }}"
  when: run_backup_now
  changed_when: false  # Running manual backups always leads to changes!

- name: Run manual stale backup deletion
  ansible.builtin.command: "{{ duplicity_binary }} remove-older-than {{ delete_backups_after }} {{ (item.backup_url_stem | default(backup_url_stem)).rstrip('/') }}/{{ (item.name | default(item.path)).strip('/') }}"  # noqa 204 - Command line too long, can't wrap
  environment: "{{ backup_env_vars | combine({'PASSPHRASE': gpg_key}) }}"
  loop: "{{ duplicity_target_paths }}"
  when: run_backup_now
  changed_when: false  # Running manual backups always leads to changes!

- name: Insert duplicity commands into crontab
  ansible.builtin.template:
    src: duplicity-backup.cron.j2
    dest: /etc/cron.d/{{ duplicity_install_name }}
    owner: root
    group: root
    mode: 0644