---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    image: leandelivery/docker-systemd:ubuntu-18.04
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    privileged: true
provisioner:
  name: ansible
scenario:
  name: default
