---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache (Ubuntu)
      apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Create source locations to backup
      file:
        path: "{{ item }}"
        state: directory
        mode: 0700
      loop:
        - /opt/awesome-config
        - /opt/other-data
        - /opt/multiple/slashes
        - /opt/separate-dest

    - name: Create some data
      copy:
        content: This is some file content
        dest: "{{ item }}"
        mode: 0600
      loop:
        - /opt/awesome-config/file-1
        - /opt/awesome-config/file-2
        - /opt/other-data/file-a
        - /opt/multiple/slashes/file-b
        - /opt/separate-dest/file-1

    - name: Purge backup destination
      file:
        path: /backupdest
        state: "{{ item }}"
        mode: 0700
      loop:
        - absent
        - directory

    - name: Purge backup destination
      file:
        path: /other-backupdest
        state: "{{ item }}"
        mode: 0700
      loop:
        - absent
        - directory

    - name: Create cron directory, because it doesn't exist in container
      file:
        path: /etc/cron.d
        state: directory
        mode: 0700
